// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUwWrcMBD9FTPt0cROu/TgW9LSshTakGvIQbXGGwVbo4zGhWXRvxdJ691s1iFbCGkv",
	"ttDMvHl686QNtDQ4smjFQ7MB397hoNLyGj2N3GJcOyaHLAZTxOj47YgHJdDAaKx8WkAJsnYIDRgruEKG",
	"UIJVQ6rfRrywsSsIYZdLv+6xlZg6tfvMqGSm6fNQjA+jYdTQ3OSs2yP4mGZsRwnASB9jU8Pi4moJJfxG",
	"9oYsNHB+Vp/VkRI5tMoZaOBj2irBKblLbCp+rA55if9IV4khu9TQwBV52WmYWaKXS9LrmNuSFbSpTDnX",
	"mzYVVvc+UpjmEFfvGTto4F21H1S1nVL1RLNwqIbwiGnDO7I+q/ihPn/17rmvRt+ycZI1zIx0VHFR1xHp",
	"MH6pdHGdFYnlodwrWm2MDrmix+yEQ2G/pP2p+1KnubAaUJA9NDcbMLFFnBVMFoyefapN+eicL5s53B5J",
	"OXOun9/zkRfHoR8kxVcarc56rXDGM99Q3vxc5Rb3YURe74F7MxiB18GirvP412DPCH6yd43g4E838Y6B",
	"YlbrOVNfFL3xUlBXTF71Oc2Nc/d/lH/j0f/jnanf5J2Z7ttLT8wpdzKE8CcAAP//QKHzaw8HAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
