// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

// Resource defines model for Resource.
type Resource struct {
	Id   *uint64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// ResourceCreate defines model for ResourceCreate.
type ResourceCreate struct {
	Name *string `json:"name,omitempty"`
}

// ResourceUpdate defines model for ResourceUpdate.
type ResourceUpdate struct {
	Name *string `json:"name,omitempty"`
}

// GetResourceIdParams defines parameters for GetResourceId.
type GetResourceIdParams struct {
	Limit  *uint64 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *uint64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostResourceJSONRequestBody defines body for PostResource for application/json ContentType.
type PostResourceJSONRequestBody = ResourceCreate

// PutResourceIdJSONRequestBody defines body for PutResourceId for application/json ContentType.
type PutResourceIdJSONRequestBody = ResourceUpdate
