openapi: 3.0.0
info:
  title: Resource API
  version: 1.0.0
paths:
  /get-room-cleanliness-status:
    post:
      summary: Upload a picture
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - picture
              properties:
                picture:
                  type: string
                  format: binary
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: string
                  prompt:
                    type: object
                    properties:
                      speech:
                        type: string
                        format: binary
                      text:
                        type: string
        '400':
          description: Bad Request